export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const GET_PLANET_SUCCESS = "GET_PLANET_SUCCESS";
export const GET_SHIP_SUCCESS = "GET_SHIP_SUCCESS";
export const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";

export const GET_PEOPLE_DETAILS_SUCCESS = "GET_PEOPLE_DETAILS_SUCCESS";
export const GET_PLANET_DETAILS_SUCCESS = "GET_PLANET_DETAILS_SUCCESS";
export const GET_SHIP_DETAIL_SUCCESS = "GET_SHIP_DETAIL_SUCCESS";
